DROP ROLE IF EXISTS DBA;
CREATE ROLE DBA;

DROP ROLE IF EXISTS TACGIA;
CREATE ROLE TACGIA;

DROP ROLE IF EXISTS NGUOIPHANBIEN;
CREATE ROLE NGUOIPHANBIEN;

DROP ROLE IF EXISTS BIENTAPVIEN;
CREATE ROLE BIENTAPVIEN;
-- DBA RIGHTS
GRANT ALL TO DBA;

-- DQL RIGHTS TO TACGIA, NGUOIPHANBIEN, BIENTAPVIEN
GRANT SELECT TO NGUOIPHANBIEN, TACGIA, BIENTAPVIEN;

-- DML RIGHTS TO TABLE FOR TACGIA, NGUOIPHANBIEN, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON NHAKHOAHOC TO TACGIA, NGUOIPHANBIEN, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON SANGTAC TO TACGIA;
GRANT INSERT, UPDATE, DELETE ON BAIPHANBIEN TO NGUOIPHANBIEN, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON PHANCONGPHANBIEN TO NGUOIPHANBIEN, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON THUCHIENPHANBIEN TO BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON THUCHIENPHANBIEN_TIEUCHIPHANBIEN TO NGUOIPHANBIEN;
GRANT INSERT, UPDATE, DELETE ON BAIBAO TO TACGIA, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON TU_KHOA TO TACGIA;
GRANT INSERT, UPDATE, DELETE ON BAIBAODADUOCCHAPNHAN TO BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON TONGQUAN TO TACGIA, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON NGHIENCUU TO TACGIA, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON PHANBIENSACH TO TACGIA, BIENTAPVIEN;
GRANT INSERT, UPDATE, DELETE ON PHANBIENSACHHASTACGIABAIBAO TO TACGIA, BIENTAPVIEN;






